const actions = {
    CREATE_RECORD: 'CREATE_RECORD',
    CREATE_RECORDS: 'CREATE_RECORDS',
    FILTER_RECORDS_BY_CLIENT_CUIT: 'FILTER_SERVICE',
    CREATE_CLIENT: 'CREATE_CLIENT',
    LIST_CLIENTS: 'LIST_CLIENTS'
}

module.exports = {
    actions
}